t3: '1.0'
info:
  id: parts-snowflake-rdb-configuration
  version: 1.0.0
  summary: SnowflakeへのDataSetアクセスを行う
  description: このシナリオファイルは、サンプルとしてSnowflakeへのDataSetアクセスを行うサンプルです。データベース名及びスキーマはSnowflakeのサンプルデータです。
configurations:
  - configuration: "RdbConnectionConfiguration"
    id: "snowflake-connection-config"
    summary: "Snowflakeに対する接続定義."
    description: "Snowflakeに対する接続定義."
    driverClassName: "net.snowflake.client.jdbc.SnowflakeDriver"
    url: "jdbc:snowflake://***.ap-northeast-1.aws.snowflakecomputing.com?db=SNOWFLAKE_SAMPLE_DATA&schema=TPCDS_SF100TCL&role=SYSADMIN&warehouse=COMPUTE_WH"
    username: "admin"
    password: "password"
    schema: "TPCDS_SF100TCL"
    rdbKind: "snowflake"
    dbName: "SNOWFLAKE_SAMPLE_DATA"